spring.application.name=SpringBoot_Project
spring.profiles.active=dev
#server.port = 8090
##--spring.config.location=./application.properties



#db
#spring.datasource.url=jdbc:mariadb://localhost:3306/portfolio
spring.datasource.url=jdbc:mariadb://49.247.19.249:3306/portfolio
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.username=root
spring.datasource.hikari.password=serversun93@
spring.datasource.hikari.maximum-pool-size=30

spring.datasource.hikari.connection-timeout=7000
spring.datasource.hikari.max-lifetime=28800000

#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#thymeleaf
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

#spring.mvc.static-path-pattern

#jsp
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

#multipart
#spring.servlet.multipart.location=/Users/seonsumin/dev/java/SpringBoot_Project/src/main/resources/static/images/
spring.servlet.multipart.location=/home/sun/api/build/libs/images/
spring.servlet.multipart.max-file-size=5MB